// Single source of truth for every path the scripts touch.
import path from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const at = (...parts) => path.join(ROOT, ...parts)

const PATHS = {
  root: ROOT,
  // inputs (source/ is fetched by `pnpm sources`, not committed)
  mainCss: at('source', 'main.css'), // admin.rosti.cz /static/ui/css/main.css (snapshot)
  styleCss: at('source', 'style.css'), // admin.rosti.cz /static/css/style.css (snapshot)
  rostiLayoutCss: at('source', 'rosti-layout.css'), // rosti.cz /_astro/Layout.*.css (design tokens)
  templatesCss: at('assets', 'templates.css'), // <style> blocks found in admin templates
  fontsCss: at('assets', 'fonts.css'), // fonts.bunny.net @font-face (latin + latin-ext)
  logoSvg: at('assets', 'logo-dark.svg'), // rosti.cz logo-green-negative2.svg, svgo-optimised
  palette: at('scripts', 'palette.mjs'), // generated by extract-palette.mjs
  aceCss: path.join(path.dirname(require.resolve('ace-builds/package.json')), 'css', 'ace.css'),
  aceCssDir: path.join(path.dirname(require.resolve('ace-builds/package.json')), 'css'),
  // outputs
  userCss: at('dist', 'rosti-dark.user.css'), // Stylus UserCSS
  siteCss: at('dist', 'dark.css'), // plain CSS for the site, @media (prefers-color-scheme: dark)
  // test harness
  fixtures: at('fixtures'),
  fontCache: at('.cache', 'fonts'),
}

/** Fixture pages every check runs against. Add new captured pages here. */
const FIXTURE_PAGES = ['login.html', 'test.html', 'ace.html', 'marketplace.html']

export { ROOT, PATHS, FIXTURE_PAGES }
